package com.andriawan.askme.ui.themes

import androidx.compose.ui.graphics.Color

val PrimaryColorLight = Color(0xFF48A4DF)
val OnPrimaryColorLight = Color(0xFFFFFFFF)
val PrimaryContainerLight = Color(0xFFC9E6FF)
val OnPrimaryContainerLight = Color(0xFF001E2F)
val SecondaryColorLight = Color(0xFF50606E)
val OnSecondaryColorLight = Color(0xFFFFFFFF)
val SecondaryContainerLight = Color(0xFFD3E5F5)
val OnSecondaryContainerLight = Color(0xFF0C1D29)
val TertiaryColorLight = Color(0xFF64597B)
val OnTertiaryColorLight = Color(0xFFFFFFFF)
val TertiaryContainerLight = Color(0xFFEADDFF)
val OnTertiaryContainerLight = Color(0xFF201634)
val BackgroundColorLight = Color(0xFFF3FBFF)
val OnBackgroundColorLight = Color(0xFF3C4856)

val PrimaryColorDark = Color(0xFF2A82BA)
val OnPrimaryColorDark = Color(0xFF00344E)
val PrimaryContainerDark = Color(0xFF004B6F)
val OnPrimaryContainerDark = Color(0xFFC9E6FF)
val SecondaryColorDark = Color(0xFFB7C9D9)
val OnSecondaryColorDark = Color(0xFF22323F)
val SecondaryContainerDark = Color(0xFF384956)
val OnSecondaryContainerDark = Color(0xFFD3E5F5)
val TertiaryColorDark = Color(0xFFCFC0E8)
val OnTertiaryColorDark = Color(0xFF352B4B)
val TertiaryContainerDark = Color(0xFF4C4162)
val OnTertiaryContainerDark = Color(0xFFEADDFF)
val BackgroundColorDark = Color(0xFF113247)
val OnBackgroundColorDark = Color(0xFFF3FBFF)

val ErrorColorLight = Color(0xFF9C413E)
val OnErrorColorLight = Color(0xFFFFFFFF)
val ErrorContainerLight = Color(0xFFFFDAD7)
val OnErrorContainerLight = Color(0xFF410005)
val ErrorColorDark = Color(0xFFFFB3AE)
val OnErrorColorDark = Color(0xFF5F1415)
val ErrorContainerDark = Color(0xFF7E2A29)
val OnErrorContainerDark = Color(0xFFFFDAD7)